server:
  port: 8082

spring:
  application:
    name: raceflow-room-service

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/rooms
    username: ${DB_USER:raceflow}
    password: ${DB_PASSWORD:secret}
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672

